run bubble:
	gcc blubble-sort.c -Wall -o blubble-sort; ./blubble-sort

run insertion:
	gcc insertion-sort.c -Wall -o insertion-sort; ./insertion-sort

run merge:
	gcc merge-sort.c -Wall -o merge-sort; ./merge-sort

run quick:
	gcc quick-sort.c -Wall -o quick-sort; ./quick-sort