run:
	gcc binary-search-tree.c -Wall -o binary-search-tree; ./binary-search-tree

debug:
	gcc -g ./binary-search-tree.c -Wall 

test:
	gcc binary-search-tree.c -Wall -o binary-search-tree; ./binary-search-tree < input.txt